### ISSUE TITLE
PHP Fatal error:  Call to a member function find() on a non-object in /Library/WebServer/Documents/zhihu/zhihu-php/zhihu/user.php on line 408

### ISSUE THREAD

**Issue by xiaoxuz** [ahonn/zhihu-php#1]
PHP Fatal error:  Call to a member function find() on a non-object in /Library/WebServer/Documents/zhihu/zhihu-php/zhihu/user.php on line 408

**Comment by ahonn** [comment]
@xiaoxuz  是否添加了你的 cookie 到 zhihu.php 中？可以提供一下使用的 URL 么~
这个错误是由于解析的页面中不存在要查找的数据而产生的。
